[package]
name = "glam-traits"
version = "0.3.0"
edition = "2021"
authors = ["Zane Jacobs"]
description = "Traits for the vectors in glam."
license = "0BSD"
repository = "https://github.com/Ababwa/glam-traits"

[dependencies]
glam = "0.30.3"
